version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  next:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
    develop:
      watch:
        - path: ./next-app/package.json
          action: rebuild
        - path: ./next-app/next.config.js
          action: rebuild
        - path: ./next-app/package-lock.json
          action: rebuild
        - path: ./next-app
          target: /app
          action: sync
